import PostsCard from "@/components/PostsCard";
import './Posts.css'

export const metadata = {
  title: 'Posts',
  description: 'Generated by Next.js',
}

async function loadPosts() {
  const res = await fetch('https://jsonplaceholder.typicode.com/posts')
  const data = await res.json();
  //await new Promise((resolve) => setTimeout(resolve, 5000))
  return data;
}

async function Posts() {
  const posts = await loadPosts();

  return (
    <div>
      <h3>Post</h3>
      <div className="grid">
        {posts.map(post => {
          return (
            <PostsCard key={post.id} post={post}></PostsCard>
          )
        })}
      </div>

    </div>

  );
}

export default Posts;